### PR TITLE
Add Prague file to class repo 

### PR DESCRIPTION
**Pull request by tomascizek**
- this is my file

@ruthtubau: what's your favorite place to have a drink in Barcelona?

### CODE REVIEW

**Comment by githubteacher** [comment]
@tomascizek what are some of your favorite restaurants in Prague?

**Comment by tomascizek** [comment]
@githubteacher: for example Di Carlo restaurant for italian food

**Comment by tomascizek** [comment]
:fire:

**Comment by githubteacher** [comment]
> @githubteacher: for example Di Carlo restaurant for italian food

@tomascizek that's awesome! feel free to add it to your hometown file

**Comment by githubteacher** [comment]
:shipit:

**Comment by xiscapericas** [comment]
Looks nice, go 🚢

**Pull request merged**
