### PR TITLE
Add Orlando file to class repo

### LINKED ISSUE #13: YOUR_USERNAME tracks progress on GitHub Flow
- [x] create a **branch** (git)
- [x] add some **commits** (git)
- [x] open a *pull request* (GitHub)
- [x] additional **commits** (git)
- [ ] _merge_ (git)

### PR DESCRIPTION
**Pull request by githubteacher**
This PR adds an Orlando file to the class repo. This PR closes #13 

- @beardofedu do you know of any good breweries in the Orlando area? 🍻 
- if you've been to Orlando before, what did you enjoy? what did you not like?
- does anyone have interest in 🍣 ? I ❤️  sushi
- what's your favorite type of food while on vacation?

### CODE REVIEW

**Comment by beardofedu** [comment]
@githubteacher I enjoy going to the following places when I am looking for a 🍺 in Orlando:
- Orlando Brewing
- Ten 10 Brewing

**Comment by bmccd** [comment]
Kobe Steakhouse!

**Comment by githubteacher** [comment]
@beardofedu @bmccd I've added your suggestions in 802b103

**Comment by githubteacher** [comment]
I'll merge when I have at least 1 👍, 🚢 , or :shipit:

**Pull request merged**
