### PR TITLE
Add some headers to Rosello File

### LINKED ISSUE #35: Albertovs tracks progress on Github Flow
- [x]  Create a branch (git)
- [x] Add some commits (git)
- [x] Open a pull request (github)
- [x] Additional commits (git)
- [ ] Merge (git)

### PR DESCRIPTION
**Pull request by Albertovs**
This PR adds an BCN file to the class repo. This PR closes #35 

- @darrenob what is your favorite drink

- Could anybody  recommend a good vietnamese restaurant in BCN?

### CODE REVIEW

**Comment by darrenob** [comment]
My favorite drink is lemonade. Sweet, sweet lemonade.

**Comment by ruthtubau** [comment]
PorSant is Catalan, Vietnamese, Chinese... whatever you want!! 🐷

**Comment by githubteacher** [comment]
:shipit:

**Comment by ashu020497** [comment]
:+1:

**Pull request merged**
